### ISSUE TITLE
--extra-data fail on binary data

### ISSUE THREAD

**Issue by kjakan** [jasonish/py-idstools#13]
idstools-u2json --output test.json --packets --extra-data snort2.log.1393411837 
WARNING: No alert message map entries loaded.
WARNING: No classifications loaded.
Traceback (most recent call last):
  File "/usr/local/bin/idstools-u2json", line 5, in <module>
    pkg_resources.run_script('idstools==0.5.0dev', 'idstools-u2json')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 528, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1394, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/idstools-0.5.0dev-py2.7.egg/EGG-INFO/scripts/idstools-u2json", line 12, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/idstools-0.5.0dev-py2.7.egg/idstools/scripts/u2json.py", line 374, in main
    encoded = json.dumps(output_filter.filter(event))
  File "/usr/lib/python2.7/json/__init__.py", line 243, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xd8 in position 272: invalid continuation byte

Possible solution to base64 encode data field:

Change from line 186:
  output_data = {
                    "data-type": data["data-type"],
                    "event-type": data["event-type"],
                    "type": data["type"],
                    "data": data["data"]
                }
to
output_data = {
                    "data-type": data["data-type"],
                    "event-type": data["event-type"],
                    "type": data["type"],
                    "data": base64.b64encode(data["data"])
                }

**Comment by jasonish** [comment]
Thanks.  I've updated the code is base64 encode the extra data payload as it can be printable or binary.
