### ISSUE TITLE
Feature Request: appid u2 support

### ISSUE THREAD

**Issue by DigiAngel** [jasonish/py-idstools#28]
This app works great with snort.u2 files...I'm wondering if you can integrate appid u2 files as well?
~~~
[15:52:26 tester:/opt/snort/var/log$] sudo idstools-u2json --snort-conf /opt/snort/etc/snort.conf -C /opt/snort/etc/classification.config -S /opt/snort/etc/sid-msg.map -G /opt/snort/etc/gen-msg.map --output /tmp/test.json --stdout appid-events-u2.log.1474407059
INFO: Loaded 48171 rule message map entries.
INFO: Loaded 70 classifications.
Traceback (most recent call last):
  File "/usr/local/bin/idstools-u2json", line 12, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/idstools/scripts/u2json.py", line 318, in main
    for record in reader:
  File "/usr/local/lib/python2.7/dist-packages/idstools/unified2.py", line 606, in next
    record = self.reader.next()
  File "/usr/local/lib/python2.7/dist-packages/idstools/unified2.py", line 569, in next
    return read_record(self.fileobj)
  File "/usr/local/lib/python2.7/dist-packages/idstools/unified2.py", line 539, in read_record
    return decode_record(rtype, buf)
  File "/usr/local/lib/python2.7/dist-packages/idstools/unified2.py", line 500, in decode_record
    return DECODERS[record_type].decode(buf)
  File "/usr/local/lib/python2.7/dist-packages/idstools/unified2.py", line 347, in decode
    values = struct.unpack(self.format, buf)
struct.error: unpack requires a string argument of length 76
~~~
Thank you.

**Comment by jasonish** [comment]
Any chance you can send me a sample of your appid-events-u2.log.1474407059.  App ID support is there, but I'm wondering if there is a configuration or compile time option, or even version variance that is causing an issue.

**Comment by DigiAngel** [comment]
Ya no sweat..I'll email it to you.

**Comment by jasonish** [comment]
Thanks for the pcap, git master now has a fix for this. Any chance you can test it out before I push out a release?

**Comment by DigiAngel** [comment]
Ya bring it...I'll git pull and test.

**Comment by DigiAngel** [comment]
Woot!:
~~~
[15:03:41 tester:/opt/snort/var/log$] sudo idstools-u2json --snort-conf /opt/snort/etc/snort.conf -C /opt/snort/etc/classification.config -S /opt/snort/etc/sid-msg.map -G /opt/snort/etc/gen-msg.map --output /tmp/test.json --stdout appid-events-u2.log.1474407059
INFO: Loaded 48171 rule message map entries.
INFO: Loaded 70 classifications.
{"event": {"impact": 0, "generator-id": 1, "protocol": 6, "dport-icode": 35253, "source-ip": "172.217.3.206", "classification-id": 0, "signature-id": 10000063, "sensor-id": 0, "impact-flag": 0, "sport-itype": 443, "priority": 0, "event-second": 1474407407, "pad2": 0, "destination-ip": "192.168.1.106", "event-id": 1, "mpls-label": 0, "vlan-id": 0, "appid": "HTTPS", "signature-revision": 0, "event-microsecond": 926775, "blocked": 0}}
{"event": {"impact": 0, "generator-id": 1, "protocol": 6, "dport-icode": 33923, "source-ip": "172.217.3.206", "classification-id": 0, "signature-id": 10000063, "sensor-id": 0, "impact-flag": 0, "sport-itype": 443, "priority": 0, "event-second": 1474407408, "pad2": 0, "destination-ip": "192.168.1.106", "event-id": 2, "mpls-label": 0, "vlan-id": 0, "appid": "HTTPS", "signature-revision": 0, "event-microsecond": 345594, "blocked": 0}}
~~~

Ya that's nice work thank you :)
