### ISSUE TITLE
idstools-rulecat: crash on Python 3.

### ISSUE THREAD

**Issue by jasonish** [jasonish/py-idstools#40]
idstools-rulecat crashes with an exception when using Python 3 and Suricata is installed:
```
[root@9d3d1f76ead0 ~]# idstools-rulecat 
Traceback (most recent call last):
  File "/usr/bin/idstools-rulecat", line 12, in <module>
    sys.exit(main())
  File "/usr/lib/python3.4/site-packages/idstools/scripts/rulecat.py", line 725, in main
    args.url.append(resolve_etopen_url(args.suricata))
  File "/usr/lib/python3.4/site-packages/idstools/scripts/rulecat.py", line 642, in resolve_etopen_url
    suricata_version = idstools.suricata.get_version(suricata_path)
  File "/usr/lib/python3.4/site-packages/idstools/suricata.py", line 61, in get_version
    m = re.search("version ((\d+)\.(\d+)\.?(\d+|\w+)?)", output.strip())
  File "/usr/lib64/python3.4/re.py", line 170, in search
    return _compile(pattern, flags).search(string)
TypeError: can't use a string pattern on a bytes-like object
```

The error is in parsing the output of "suricata -V".

**Comment by jasonish** [comment]
Fixed with commit https://github.com/jasonish/py-idstools/commit/43c29e7384d38709a3146ca7d76ab7cdfa35bc23
