### ISSUE TITLE
u2spewfoo.py KeyError

### ISSUE THREAD

**Issue by DigiAngel** [jasonish/py-idstools#45]
An odd one.  I don't get this with the one in tests dir:
~~~
(Event)
u2spewfoo.py(116):     for row in rows:
u2spewfoo.py(117):         parts = ["%s: %s" % (col[0], col[2](event[col[1]])) for col in row]
u2spewfoo.py(117):         parts = ["%s: %s" % (col[0], col[2](event[col[1]])) for col in row]
u2spewfoo.py(117):         parts = ["%s: %s" % (col[0], col[2](event[col[1]])) for col in row]
u2spewfoo.py(117):         parts = ["%s: %s" % (col[0], col[2](event[col[1]])) for col in row]
u2spewfoo.py(117):         parts = ["%s: %s" % (col[0], col[2](event[col[1]])) for col in row]
u2spewfoo.py(118):         print("\t" + "\t".join(parts))
	sensor id: 0	event id: 1	event second: 1490338878	event microsecond: 955846
u2spewfoo.py(116):     for row in rows:
u2spewfoo.py(117):         parts = ["%s: %s" % (col[0], col[2](event[col[1]])) for col in row]
u2spewfoo.py(117):         parts = ["%s: %s" % (col[0], col[2](event[col[1]])) for col in row]
u2spewfoo.py(117):         parts = ["%s: %s" % (col[0], col[2](event[col[1]])) for col in row]
u2spewfoo.py(117):         parts = ["%s: %s" % (col[0], col[2](event[col[1]])) for col in row]
u2spewfoo.py(117):         parts = ["%s: %s" % (col[0], col[2](event[col[1]])) for col in row]
u2spewfoo.py(118):         print("\t" + "\t".join(parts))
	sig id: 2402000	gen id: 1	revision: 4391	classification: 30
u2spewfoo.py(116):     for row in rows:
u2spewfoo.py(117):         parts = ["%s: %s" % (col[0], col[2](event[col[1]])) for col in row]
u2spewfoo.py(117):         parts = ["%s: %s" % (col[0], col[2](event[col[1]])) for col in row]
 --- modulename: u2spewfoo, funcname: print_address
u2spewfoo.py(83):     if len(addr) <= 15:
u2spewfoo.py(84):         return addr
u2spewfoo.py(117):         parts = ["%s: %s" % (col[0], col[2](event[col[1]])) for col in row]
 --- modulename: u2spewfoo, funcname: print_address
u2spewfoo.py(83):     if len(addr) <= 15:
u2spewfoo.py(84):         return addr
u2spewfoo.py(117):         parts = ["%s: %s" % (col[0], col[2](event[col[1]])) for col in row]
u2spewfoo.py(118):         print("\t" + "\t".join(parts))
	priority: 2	ip source: 91.223.133.13	ip destination: x.x.x.x
u2spewfoo.py(116):     for row in rows:
u2spewfoo.py(117):         parts = ["%s: %s" % (col[0], col[2](event[col[1]])) for col in row]
u2spewfoo.py(117):         parts = ["%s: %s" % (col[0], col[2](event[col[1]])) for col in row]
u2spewfoo.py(117):         parts = ["%s: %s" % (col[0], col[2](event[col[1]])) for col in row]
u2spewfoo.py(117):         parts = ["%s: %s" % (col[0], col[2](event[col[1]])) for col in row]
u2spewfoo.py(117):         parts = ["%s: %s" % (col[0], col[2](event[col[1]])) for col in row]
u2spewfoo.py(117):         parts = ["%s: %s" % (col[0], col[2](event[col[1]])) for col in row]
u2spewfoo.py(118):         print("\t" + "\t".join(parts))
	src port: 58978	dest port: 8899	protocol: 6	impact_flag: 0	blocked: 0
u2spewfoo.py(116):     for row in rows:
u2spewfoo.py(117):         parts = ["%s: %s" % (col[0], col[2](event[col[1]])) for col in row]
u2spewfoo.py(117):         parts = ["%s: %s" % (col[0], col[2](event[col[1]])) for col in row]
u2spewfoo.py(117):         parts = ["%s: %s" % (col[0], col[2](event[col[1]])) for col in row]
 --- modulename: trace, funcname: _unsettrace
trace.py(80):         sys.settrace(None)
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/lib/python2.7/trace.py", line 819, in <module>
    main()
  File "/usr/lib/python2.7/trace.py", line 807, in main
    t.runctx(code, globs, globs)
  File "/usr/lib/python2.7/trace.py", line 513, in runctx
    exec cmd in globals, locals
  File "bin/idstools-u2spewfoo", line 12, in <module>
    sys.exit(main())
  File "/home//nobackup/build/py-idstools/idstools/scripts/u2spewfoo.py", line 191, in main
    print_record(record)
  File "/home/nobackup/build/py-idstools/idstools/scripts/u2spewfoo.py", line 173, in print_record
    print_event(record)
  File "/home/nobackup/build/py-idstools/idstools/scripts/u2spewfoo.py", line 117, in print_event
    parts = ["%s: %s" % (col[0], col[2](event[col[1]])) for col in row]
KeyError: 'pad2'
~~~

Running latest snort-2.9.9.0.  Anything I can do to troubleshoot on this end?  Running the u2spewfoo that comes with snort runs fine.  Thank you.

**Comment by jasonish** [comment]
I'm going to have to retest with Snort 2.9.9.0.  Can you also tell me your compile options? Or if you installed from a package? Different compile time options can alter the unified2 layout and its possible I don't support all combinations yet.

Or perhaps send me your unified2 file that is erroring out if you can? Email privately at ish@unx.ca if you can.

**Comment by DigiAngel** [comment]
Sent alone...and for those watching from home my compile line is:
~~~
./configure --prefix=/opt --enable-non-ether-decoders --enable-sourcefire --enable-shared-rep --enable-control-socket --enable-open-appid
~~~

Thank you!

**Comment by jasonish** [comment]
Fixed with commit https://github.com/jasonish/py-idstools/commit/baa8a6f4e5b0065665fc6b03dff49d0f96d9e605

Thanks!
