### ISSUE TITLE
Issues with rulecat.py and Python3

### ISSUE THREAD

**Issue by marcindulak** [jasonish/py-idstools#53]
```
cd /tmp
git clone https://github.com/jasonish/py-idstools
cd py-idstools
git rev-parse HEAD
#6821df33bfaaf39331cf27843144d48cc3f9b8dc
PYTHONPATH=. python3 bin/idstools-rulecat -o /etc/suricata/rules
2017-05-18 11:20:43,213 - <INFO> -- Found Suricata version 3.2.1 at /usr/sbin/suricata.
Traceback (most recent call last):
  File "bin/idstools-rulecat", line 12, in <module>
    sys.exit(main())
  File "/tmp/py-idstools/idstools/scripts/rulecat.py", line 766, in main
    files = Fetch(args).run()
  File "/tmp/py-idstools/idstools/scripts/rulecat.py", line 284, in run
    files.update(self.fetch(url))
  File "/tmp/py-idstools/idstools/scripts/rulecat.py", line 262, in fetch
    tmp_filename = self.get_tmp_filename(url)
  File "/tmp/py-idstools/idstools/scripts/rulecat.py", line 251, in get_tmp_filename
    url_hash = hashlib.md5(url).hexdigest()
TypeError: Unicode-objects must be encoded before hashing
```
See https://bugzilla.redhat.com/show_bug.cgi?id=1452025

**Comment by jasonish** [comment]
Fixed this and some other Python 3 in git master...  I have to admit, I need to tighten up on some of the string/unicode/byte buffer handling for Python 3. So while the command above now completes, there are probably still some Python 3 buffer handling issues.

**Comment by marcindulak** [comment]
Works for me. Please consider a new release soon.

**Comment by jasonish** [comment]
Ok. Just hoping to resolve #54 first.

**Comment by jasonish** [comment]
> Works for me. Please consider a new release soon.

Done. 0.6.1. This and many more Python 3 fixups - well unicode fixups.
